---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koy
  labels:
    app: koy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: koy
  template:
    metadata:
      labels:
        app: koy
    spec:
      containers:
        - name: koy
          image: docker.io/phengbunath/koy:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
